### ISSUE TITLE
Test failed in macOS

### ISSUE THREAD

**Issue by Pancf** [mruby/mruby#6026] opened 2023-06-23 12:18 UTC
OS: macOS 13.3.1
branch: master
how to reproduce: `rake all test`
expect: build and run test successfully
what fail:
```>>> Bintest host <<<
bintest - Command Binary Test

...XXXXX....X........FFFFF.F........X...............................................................
ArgumentError: mruby-bin-debugger(mrdb) command line => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:72:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:62:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
ArgumentError: mruby-bin-debugger(mrdb) command: "break" => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:85:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:75:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
ArgumentError: mruby-bin-debugger(mrdb) command: "continue" => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:96:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:91:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
ArgumentError: mruby-bin-debugger(mrdb) command: "delete" => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:118:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:105:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
ArgumentError: mruby-bin-debugger(mrdb) command: "disable" => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:133:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:121:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
ArgumentError: mruby-bin-debugger(mrdb) command: "list" => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `split'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:35:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:23:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:219:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/mrdb.rb:206:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
Fail: mruby-bin-debugger(print) scope:class (mrbgems: mruby-bin-debugger)
 - Assertion[2]
    Expected "$1 = end\n" to be start_with? "$1 = TestClassScope".
Fail: mruby-bin-debugger(print) scope:module (mrbgems: mruby-bin-debugger)
 - Assertion[2]
    Expected "$1 = end\n" to be start_with? "$1 = TestModuleScope".
Fail: mruby-bin-debugger(print) scope:instance method (mrbgems: mruby-bin-debugger)
 - Assertion[2]
    Expected "$1 = #<m:0x7fcda0008fc0>\n" to be start_with? "$1 = #<TestMethodScope:".
Fail: mruby-bin-debugger(print) scope:class method (mrbgems: mruby-bin-debugger)
 - Assertion[2]
    Expected "$1 = cm\n" to be start_with? "$1 = TestClassMethodScope".
Fail: mruby-bin-debugger(print) scope:block (mrbgems: mruby-bin-debugger)
 - Assertion[5]
    Expected "$2 = m\n" to be start_with? "$2 = TestBlockScope".
Fail: mruby-bin-debugger(print) same name:instance variable (mrbgems: mruby-bin-debugger)
 - Assertion[4]
    Expected "$1 = nil\n" to be start_with? "$1 = \"instance1\"".
ArgumentError: mruby-bin-debugger(print) Ternary operation => invalid byte sequence in UTF-8 (mrbgems: mruby-bin-debugger)
backtrace:
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:27:in `skip_until'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:27:in `block in test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:24:in `each'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:24:in `test'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:572:in `block in <top (required)>'
        /Users/focus/opensource/mruby/test/assert.rb:101:in `assert'
        /Users/focus/opensource/mruby/mrbgems/mruby-bin-debugger/bintest/print.rb:551:in `<top (required)>'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `load'
        /Users/focus/opensource/mruby/test/bintest.rb:52:in `block (2 levels) in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:50:in `block in <main>'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `each'
        /Users/focus/opensource/mruby/test/bintest.rb:40:in `<main>'
  Total: 100
     OK: 87
     KO: 6
  Crash: 7
Warning: 0
   Skip: 0
   Time: 4.13 seconds
rake aborted!
Command failed with status (1): [BUILD_DIR=/Users/focus/opensource/mruby/bu...]
/Users/focus/opensource/mruby/lib/mruby/build.rb:470:in `run_bintest'
/Users/focus/opensource/mruby/tasks/test.rake:59:in `block (2 levels) in <top (required)>'
/Users/focus/opensource/mruby/tasks/test.rake:3:in `block in <top (required)>'
Tasks: TOP => test:run => test:run:bin:host
(See full trace by running task with --trace)```

**Comment by dearblue** [comment] 2023-06-25 11:34
This issue is the same reason why #6005 has not been merged yet.
In my opinion, I suspect that `bin/mrbc -d` may have a problem.

**Comment by Pancf** [comment] 2023-06-26 13:42
> This issue is the same reason why #6005 has not been merged yet.
> In my opinion, I suspect that `bin/mrbc -d` may have a problem.

When I turn on `conf.enable_debug` in build_config/default.rb, there is no error

**Comment by Pancf** [comment] 2023-07-14 11:23
master branch still has this problem, anyone knows the reason?

**Comment by matz** [comment] 2023-11-12 02:27
Maybe caused by clang version 13. What version of clang are you using?

**Comment by Pancf** [comment] 2023-11-13 07:38
> Maybe caused by clang version 13. What version of clang are you using?

My os has been upgraded to macOS 14.1.1, and I can't reproduce error with the latest master branch.

**Comment by matz** [comment] 2023-11-18 13:43
OK, close this issue right now. Please reopen if you see the problem again.
General advice: avoid clang 13 to compile mruby.

**Closed by matz** 2023-11-18 13:43 UTC
