### ISSUE TITLE
Numerics don't respond to arithmetic operators

### ISSUE THREAD

**Issue by aquila12** [mruby/mruby#5024] opened 2020-06-19 15:22 UTC
Numerics don't seem to respond to the likes of :+, :*, :/, etc.  This is strange coming from Ruby, as the typical way to do sum / product of an array is `@array.inject(:+)` - this throws an exception.

I saw from another issue that mruby uses specific opcodes for arithmetic, but I'd have still expected those classes to respond to the calls if they're dispatched.

**Comment by matz** [comment] 2020-06-19 23:28
Could you describe your situation and configuration? What kind of exception did you get?
My `mruby` works, e.g.
```ruby
@array = [1,2,3.5]
p @array.inject(:+)
# => 6.5
```

**Comment by aquila12** [comment] 2020-06-20 20:07
Hmm, this might be a peculiarity of the version / build that DragonRuby is using.  I'll throw it up there and see if anyone bites and get back to you - apologies.
The output I get, in case it is anything to do with mruby, is:
```
-> @a = [1,2,3.5]
=> [1, 2, 3.5]
-> @a
=> [1, 2, 3.5]
-> p @a.inject(:+)
* ERROR:
** method_missing: +
** instance:       1
** on class:       Fixnum
** with modules:   [Integral, NumericDeprecated, ValueType, Comparable, Kernel]
** with values:    1
** given args:     [[2]]
** exception:      can't define singleton
```

**Comment by matz** [comment] 2020-06-21 04:00
Hmm, we don't know about `NumericDeprecated` and `ValueType`. So it strongly suggests the issue was caused by the modification outside of `mruby`. I will close the issue for now. Don't hesitate to reopen it if you see anything related to `mruby` core.

**Closed by matz** 2020-06-21 04:00 UTC
