### ISSUE TITLE
Segmentation fault when opening Module class

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4460] opened 2019-05-21 06:30 UTC
EDIT: this original bug report is bogus. The segmentation fault occurs when calling a method on an `mrb_value` with tt `MRB_TT_UNDEF` via `mrb_funcall_argv`.

There is something funky going on when opening the `Module` class with `mrb_load_nstring_cxt` that results in a segmentation fault:

Segfault:

```ruby
class Module; def autoload(a, b); end; end
```

Segfault:

```ruby
class Module; def autoload(*rest); end; end

```
No segfault:

```ruby
class Module; def autoload; end; end
```

No segfault:

```ruby
class Module; 42; end
```

I can't tell if the segfault occurs when the method is defined or when it is invoked.

I am currently using mruby 2.0.1 as of commit c078758.

**Comment by lopopolo** [comment] 2019-05-21 06:34
This code segfaults too:

```
class Module; def autoload(*rest); end; end
```

**Comment by matz** [comment] 2019-05-21 08:02
I cannot reproduce the error. Can you give us more information? Your CPU, OS, program to execute the script, etc?

**Comment by lopopolo** [comment] 2019-05-21 08:11
Hi @matz, I posted this bug report prematurely. Due to an error on my part, I was calling a method with `mrb_funcall_argv` on a `mrb_value` with tt = `MRB_TT_UNDEF`.

**Comment by matz** [comment] 2019-05-21 08:31
May I close this issue?

**Comment by lopopolo** [comment] 2019-05-21 08:32
Are function calls on Undef supposed to segfault?

**Comment by matz** [comment] 2019-05-21 08:57
Yes. `undef` value is not supposed to be exposed to the VM (Ruby World).

**Closed by matz** 2019-05-21 08:57 UTC
