### ISSUE TITLE
How disable gem mruby-io

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#3961] opened 2018-02-27 08:33 UTC
Is possible to turn off all disk function on mruby?
Acessing file is sometimes dangerous.

is possible add this in to turn off if needed?
```
MRuby::GemBox.new do |conf|
end
```

and socket

**Comment by shevegen** [comment] 2018-02-27 22:42
Reminds me a bit of my proposals in regards to easy static binaries of MRI ruby. I am glad that other people also have somewhat similar ideas. \o/
Like a containerized mini-ruby-OS.

**Comment by take-cheeze** [comment] 2018-02-28 00:29
@letarg0 Paste your `build_config.rb` or build log first.

**Comment by letarg0** [comment] 2018-02-28 06:41
@take-cheeze my build_config.rb is default. I'm no have option to disable mruby-io because it is not exist in build_config.rb .

**Comment by take-cheeze** [comment] 2018-02-28 06:51
https://github.com/mruby/mruby/blob/097bfdcac573861567716e4247265becec6b249a/mrbgems/default.gembox#L3
is the cause so remove all
```
  conf.gembox 'default'
```
and add mrbgems you use instead.

**Comment by take-cheeze** [comment] 2018-02-28 06:53
Define `MRB_DISABLE_STDIO` preprocessor macro somewhere too.

**Comment by texrg** [comment] 2018-02-28 08:20
My conf is good?
I cant use `File.open`

https://gist.github.com/texrg/20e3ce008a653c26ef0b6e4610b22441

**Comment by letarg0** [comment] 2018-02-28 10:01
I'm not found mruby-io on default.gembox
This is good idea to remove all

**Comment by and09** [comment] 2018-03-05 18:00
Thanks

**Comment by matz** [comment] 2018-03-12 14:46
May I close the issue, or is there any remaining issue?

**Comment by letarg0** [comment] 2018-03-13 12:36
Yes

**Closed** 2018-03-13 12:36 UTC
