### ISSUE TITLE
Mruby build issue with latest version

### ISSUE THREAD

**Issue by Zogoo** [mruby/mruby#4934] opened 2020-01-20 11:30 UTC
I'm working on some ngx_mruby project recently main master branch switched to latest mruby version. So, I have got following mruby related issues. 

Environment: OSX, Clang

Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0

Symbol not found _mrb_sym2str

```
nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_mruby_module.so" failed (dlopen(/usr/local/nginx/modules/ngx_http_mruby_module.so, 10): Symbol not found: _mrb_sym2str
  Referenced from: /usr/local/nginx/modules/ngx_http_mruby_module.so
  Expected in: flat namespace
 in /usr/local/nginx/modules/ngx_http_mruby_module.so) in /usr/local/nginx/conf/nginx.conf:12
```
And then when I run rake in the mruby folder I have got another issue.

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command Failed: [gcc  -o /Users/ngx_mruby/mruby/build/host/bin/mruby-strip /Users/ngx_mruby/mruby/build/host/mrbgems/mruby-bin-strip/tools/mruby-strip/mruby-strip.o /Users/ngx_mruby/mruby/build/host/lib/libmruby.a  -lm -lreadline -lncurses ]
```

Is there anything changed in the build process?

**Comment by shuujii** [comment] 2020-01-20 12:14
> Symbol not found _mrb_sym2str
> 
> ```
> nginx: [emerg] dlopen() "/usr/local/nginx/modules/ngx_http_mruby_module.so" failed (dlopen(/usr/local/nginx/modules/ngx_http_mruby_module.so, 10): Symbol not found: _mrb_sym2str
>   Referenced from: /usr/local/nginx/modules/ngx_http_mruby_module.so
>   Expected in: flat namespace
>  in /usr/local/nginx/modules/ngx_http_mruby_module.so) in /usr/local/nginx/conf/nginx.conf:12
> ```

You may need to full rebuild ngx_mruby because `mrb_sym2str` has become a macro.

> And then when I run rake in the mruby folder I have got another issue.
> 
> ```
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> rake aborted!
> Command Failed: [gcc  -o /Users/ngx_mruby/mruby/build/host/bin/mruby-strip /Users/ngx_mruby/mruby/build/host/mrbgems/mruby-bin-strip/tools/mruby-strip/mruby-strip.o /Users/ngx_mruby/mruby/build/host/lib/libmruby.a  -lm -lreadline -lncurses ]
> ```

`toolchain` in `build_config.rb` should be `:clang` If you use Clang.

**Comment by shuujii** [comment] 2020-01-20 14:21
> > And then when I run rake in the mruby folder I have got another issue.
> > ```
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > rake aborted!
> > Command Failed: [gcc  -o /Users/ngx_mruby/mruby/build/host/bin/mruby-strip /Users/ngx_mruby/mruby/build/host/mrbgems/mruby-bin-strip/tools/mruby-strip/mruby-strip.o /Users/ngx_mruby/mruby/build/host/lib/libmruby.a  -lm -lreadline -lncurses ]
> > ```
> 
> `toolchain` in `build_config.rb` should be `:clang` If you use Clang.

Sorry, I misread the log a bit.

Are any missing symbols output before `ld: symbol(s) not found for architecture x86_64`? If it is `_mrb_sym2str`, you need to fully rebuild also mruby. Normally, mruby will be rebuilt if `build_config.rb` (`toolchain`) is modified.

**Comment by Zogoo** [comment] 2020-01-21 01:27
@shuujii thanks for the quick reply. I will try to reconfigure my build_config and rebuild it.
2nd issue was my bad because ngx_mruby uses external build_config file I forgot that part.

**Comment by Zogoo** [comment] 2020-01-21 02:52
@shuujii I could solve the issue when I delete whole build folder.
Before I tried like follows 
```
./minirake clean 
rake  
ruby minirake
make
```

**Comment by matz** [comment] 2020-01-21 04:50
The first error (concerning `_mrb_sym2str`) was caused by the version mismatch between `ngx_mruby` and `mruby`. You have to recompile both `ngx_mruby` and `mruby`.
The second error is a mystery. I believe clang ld is kind enough to show the missing symbols. Could you show the whole error messages?

**Comment by shuujii** [comment] 2020-01-21 08:13
> I think the clean task not working properly.

`NGX_MRUBY_ROOT/build_config.rb` is used when using `build.sh` or `make build_mruby` of ngx_mruby. However, `NGX_MRUBY_ROOT/mruby/build_config.rb` is used when you just run `rake clean` in `NGX_MRUBY_ROOT/mruby` directory.

So, specifying `build_config.rb` to use as follows may work as expected:

  ```console
  $ cd NGX_MRUBY_ROOT/mruby
  $ rake clean MRUBY_CONFIG=NGX_MRUBY_ROOT/build_config.rb
  ```

**Comment by Zogoo** [comment] 2020-01-22 09:09
> The first error (concerning `_mrb_sym2str`) was caused by the version mismatch between `ngx_mruby` and `mruby`. You have to recompile both `ngx_mruby` and `mruby`.
> The second error is a mystery. I believe clang ld is kind enough to show the missing symbols. Could you show the whole error messages?

Second one was my fault I just forgot ngx_mruby was using external build_config.rb file through the MRUBY_CONFIG. And I did it with default build_config.rb of mruby repo.

**Comment by Zogoo** [comment] 2020-01-22 09:09
> > I think the clean task not working properly.
> 
> `NGX_MRUBY_ROOT/build_config.rb` is used when using `build.sh` or `make build_mruby` of ngx_mruby. However, `NGX_MRUBY_ROOT/mruby/build_config.rb` is used when you just run `rake clean` in `NGX_MRUBY_ROOT/mruby` directory.
> 
> So, specifying `build_config.rb` to use as follows may work as expected:
> 
> ```
> $ cd NGX_MRUBY_ROOT/mruby
> $ rake clean MRUBY_CONFIG=NGX_MRUBY_ROOT/build_config.rb
> ```

I see. Thanks for your help.

**Comment by matz** [comment] 2020-01-28 04:51
May I close this issue?

**Comment by Zogoo** [comment] 2020-02-03 06:08
@matz  sorry for for delayed answer. I haven't tried yet. For now let me close it by myself. 
If I face some issues with version upgrade let me reopen it later. 
Thanks.

**Closed** 2020-02-03 06:09 UTC
