### ISSUE TITLE
Undefined reference to `GENERATED_TMP_mrb_mruby_eval_gem_final' on Linux

### ISSUE THREAD

**Issue by ashes999** [mruby/mruby#2872] opened 2015-07-02 23:04 UTC
Hi,

I've managed to build mruby on Ubuntu 14.04. I'm trying to cross-build to Android, which should work according to [this issue](https://github.com/mruby/mruby/issues/2039). I've added this to the end of my `build_config.rb`:

```
MRuby::CrossBuild.new('androideabi') do |conf|
   toolchain :androideabi
end
```

I have downloaded the SDK/NDK, and I think I've set up the android toolchain correctly. I have:

- `ANDROID_NDK_HOME` defined
- `SYSROOT` defined
- The android toolchain binaries in my `PATH`
- `ANDROID_STANDALONE_TOOLCHAIN` defined

Below is the stack I get when I run `./minirake`. What am I doing wrong?

```
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/lib/libmruby.a(gem_init.o): In function `mrb_init_mrbgems':
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/gem_init.c:107: undefined reference to `GENERATED_TMP_mrb_mruby_eval_gem_init'
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/lib/libmruby.a(gem_init.o): In function `mrb_final_mrbgems':
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/gem_init.c:81: undefined reference to `GENERATED_TMP_mrb_mruby_eval_gem_final'
collect2: error: ld returned 1 exit status
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/lib/libmruby.a(gem_init.o): In function `mrb_init_mrbgems':
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/gem_init.c:107: undefined reference to `GENERATED_TMP_mrb_mruby_eval_gem_init'
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/lib/libmruby.a(gem_init.o): In function `mrb_final_mrbgems':
/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/gem_init.c:81: undefined reference to `GENERATED_TMP_mrb_mruby_eval_gem_final'
collect2: error: ld returned 1 exit status
rake aborted!
Command Failed: [gcc  -o "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/bin/mrdb" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/cmdrun.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/apiprint.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/cmdmisc.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/cmdbreak.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/cmdprint.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/mrbgems/mruby-bin-debugger/tools/mrdb/apilist.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host-debug/lib/libmruby.a"  -lm
```

**Comment by matz** [comment] 2015-07-03 06:02
when you see this kind of problem, try `rake clean` first.

**Comment by ashes999** [comment] 2015-07-03 08:21
@matz I had tried `./minirake clean` but not `rake clean`. The latter gives me a quicker failure with a different error: `error adding symbols: File in wrong format`

```
/usr/bin/ld: /home/ashiq/Desktop/mruby-1.1.0/build/host/tools/mrbc/mrbc.o: Relocations in generic ELF (EM: 40)
/home/ashiq/Desktop/mruby-1.1.0/build/host/tools/mrbc/mrbc.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
rake aborted!
Command Failed: [gcc  -o "/home/ashiq/Desktop/mruby-1.1.0/build/host/bin/mrbc" "/home/ashiq/Desktop/mruby-1.1.0/build/host/tools/mrbc/mrbc.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host/lib/libmruby_core.a"  -lm ]
```

**Comment by ashes999** [comment] 2015-07-03 09:20
I'm pretty sure this is an environmental problem on my end. I think I'm getting a mix of compiler tools used during compilation.

Sorry, I'm not a very experienced C/C++ developer.  Please tell me if the following exports should or shouldn't be defined as they are.

- `ANDROID_NDK_HOME` (location of the NDK files)
- `NDK` (alias for the above)
- `SYSROOT` (`$NDK/platforms/android-14/arch-arm`)
- `CC` (`arm-linux-androideabi-gcc`)
- `ANDROID_STANDALONE_TOOLCHAIN` (path to my toolchain generated with `$NDK/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm`)

**Comment by joans321** [comment] 2015-07-23 05:05
Android cross compile only need to export *ANDROID_STANDALONE_TOOLCHAIN*.
Do like these :
* rake clean or rm -rf build
* export ANDROID_STANDALONE_TOOLCHAIN=<path toolchain generated by ndk>
* rake -vvv

**Comment by ashes999** [comment] 2015-07-23 14:14
@joans321 I'm getting a different error; it looks like it's trying to compile `bin/mrbc`:

```
/home/ashiq/Desktop/my-android-toolchain/bin/arm-linux-androideabi-ar: creating /home/ashiq/Desktop/mruby-1.1.0/build/host/lib/libmruby_core.a
"/home/ashiq/Desktop/my-android-toolchain/bin/arm-linux-androideabi-gcc" -mandroid --sysroot="/home/ashiq/Desktop/my-android-toolchain/sysroot" -o "/home/ashiq/Desktop/mruby-1.1.0/build/host/bin/mrbc" "/home/ashiq/Desktop/mruby-1.1.0/build/host/tools/mrbc/mrbc.o" "/home/ashiq/Desktop/mruby-1.1.0/build/host/lib/libmruby_core.a"  -lm 
/home/ashiq/Desktop/mruby-1.1.0/build/host/bin/mrbc: 1: /home/ashiq/Desktop/mruby-1.1.0/build/host/bin/mrbc: Syntax error: word unexpected (expecting ")")
```

Does it matter that I'm using mruby at the 1.1.0 release branch?

**Comment by joans321** [comment] 2015-07-24 01:11
I think you need switch to the lastest master branch !

**Comment by matz** [comment] 2015-11-16 14:40
I close this because I think this one was caused by cross compiling inconsistency.
If you can reproduce the error at the master (which is going to be 1.2.0 release),
reopen the issue.

**Closed by matz** 2015-11-16 14:40 UTC
